%YAML:1.0
aruco_bc_nmarkers: 9
aruco_bc_mInfoType: 1
aruco_bc_markers:
   - { id:7, corners:[ [ -50., -50., 0. ], [ 50., -50., 0. ], [ 50., 50., 0. ],
       [ -50., 50., 0. ] ] }
   - { id:213, corners:[ [ -50., -50., 0. ], [ 50., -50., 0. ], [ 50., 50., 0. ],
       [ -50., 50., 0. ] ] }
   - { id:225, corners:[ [ -50., -50., 0. ], [ 50., -50., 0. ], [ 50., 50., 0. ],
       [ -50., 50., 0. ] ] }
   - { id:322, corners:[ [ -50., -50., 0. ], [ 50., -50., 0. ], [ 50., 50., 0. ],
       [ -50., 50., 0. ] ] }
   - { id:1, corners:[ [ -50., -50., 0. ], [ 50., -50., 0. ], [ 50., 50., 0. ],
       [ -50., 50., 0. ] ] }
   - { id:373, corners:[ [ -50., -50., 0. ], [ 50., -50., 0. ], [ 50., 50., 0. ],
       [ -50., 50., 0. ] ] }
   - { id:984, corners:[ [ -50., -50., 0. ], [ 50., -50., 0. ], [ 50., 50., 0. ],
       [ -50., 50., 0. ] ] }
   - { id:156, corners:[[ -50., -50., 0. ], [ 50., -50., 0. ], [ 50., 50., 0. ],
       [ -50., 50., 0. ] ] }
   - { id:985, corners:[ [ -50., -50., 0. ], [ 50., -50., 0. ], [ 50., 50., 0. ],
       [ -50., 50., 0. ] ] }
